### PR TITLE
#1555: Documentation of Federation with FedX

### PR DESCRIPTION
**Pull request by aschwarte10**
* Getting Started
* Java Applications
* FedX Configuration
* Member configuration
* Monitoring and Logging

### CODE REVIEW

**Comment by aschwarte10** [comment]
@jeenbroekstra this is the main part of the documentation (focussing on programming / using FedX). It is mostly an adoption of the already existing documentation.

As a second part I am planning to add how Federation can be used in the workbench. The current steps as of https://github.com/VeritasOS/fedx/wiki/FedX-in-RDF4J-Server are too complex, and I am planning to achieve a more seamless integration (which is particularly possible to the more tight integration with RDF4J). The more seamless integration will be worked on in the next two weeks, I will track this also as an issue and provide more details

**Review by abrokenjester — APPROVED** [review]
This looks great, thanks @aschwarte10 !

**Comment by aschwarte10** [comment]
@jeenbroekstra quick question: can you shortly confirm that the develop branch also the right target here?

**Comment by abrokenjester** [comment]
Develop is the right branch, thanks @aschwarte10!

**Pull request merged**
