### PR TITLE
3.3.0-m1

### PR DESCRIPTION
**Pull request by hmottestad**

### CODE REVIEW

**Comment by hmottestad** [comment]
@jeenbroekstra build is published and links for downloading the SDK work. I've created a very simple news item. I know there are a lot of contributors to mention, but I thought we would hold out for the actual release for that. Do you agree? Any comments to the news item?

**Comment by abrokenjester** [comment]
Yep agreed, keep it short for the milestone news item. I'd just copy-paste what we did for the 3.2 milestone builds, just update relevant links. No release notes or acknowledgments yet.

**Review by abrokenjester — APPROVED** [review]
Looks good, though kind of surprised you added the javadoc - I don't typically do that for milestones. In this case it kinda makes sense  though as there are some API changes.

**Comment by abrokenjester** [comment]
Oops, accidently clicked "re-request review" for myself. Happy with this, I'll leave it to you to merge (assuming you want to time with a mail to the user list) @hmottestad .

**Comment by hmottestad** [comment]
That was my plan.

**Pull request merged**
