### PR TITLE
Fix typo "example on hot" to "examples on how"

### PR DESCRIPTION
**Pull request by zacharywhitley**

### CODE REVIEW

**Comment by abrokenjester** [comment]
Thanks @ZacharyWhitley .

Could you please digitally sign the Eclipse Contributor Agreement (ECA)? See the [Contributor Guidelines](https://github.com/eclipse/rdf4j-doc/blob/master/.github/CONTRIBUTING.md) for more details on how to sign. Unfortunately, we cannot accept your contribution until you have signed this. It shouldn't take more than 5 minutes.

**Comment by zacharywhitley** [comment]
Will do. Should get to that tonight.

**Comment by zacharywhitley** [comment]
Signed

**Comment by abrokenjester** [comment]
Great, thanks! There's still a failing check, but this is caused by a bug in the validation script I think. I'll merge and republish this asap.

**Pull request merged**
